### ISSUE TITLE
Arctis 1 Wireless [Failed to access device: HidApiError]

### ISSUE THREAD

**Issue by gamerscircle** [aarol/arctis-battery-indicator#3]
I see that your did create an entry for my headset and I did my best to read thought your documentation, but I am not sure what I should do to help resolve this.

15:05:05 [INFO] Starting application
15:05:05 [INFO] Searching for connected headphones...
15:05:06 [INFO] Found headphone: SteelSeries Arctis 1 Wireless
15:05:07 [ERROR] Failed to access device: HidApiError { message: "WriteFile: (0x00000001) Incorrect function." }; trying to reconnect...
15:05:07 [INFO] Searching for connected headphones...
15:05:07 [INFO] Found headphone: SteelSeries Arctis 1 Wireless
15:05:07 [ERROR] Failed to access device: HidApiError { message: "WriteFile: (0x00000001) Incorrect function." }; trying to reconnect...
15:05:09 [INFO] Searching for connected headphones...
15:05:09 [INFO] Found headphone: SteelSeries Arctis 1 Wireless
15:05:09 [ERROR] Failed to access device: HidApiError { message: "WriteFile: (0x00000001) Incorrect function." }; trying to reconnect...

**Comment by aarol** [comment]
Hello! I just pushed a new version (1.5.0) which should hopefully fix this. Can you give it a try and report back?

**Comment by gamerscircle** [comment]
I did, thank you and here is the debug information.
11:42:54 [INFO] Starting application
11:42:54 [TRACE] (1) arctis_battery_indicator: [src\lib.rs:42] Using locale en-US
[src\lib.rs:43:5] rust_i18n::available_locales!() = [
    "en-US",
    "fi-FI",
]
11:42:54 [INFO] Searching for connected headphones...
11:42:54 [INFO] Found headphone: SteelSeries Arctis 1 Wireless
11:42:55 [ERROR] Failed to access device: HidApiError { message: "WriteFile: (0x00000001) Incorrect function." }; trying to reconnect...
11:42:55 [INFO] Searching for connected headphones...
11:42:55 [INFO] Found headphone: SteelSeries Arctis 1 Wireless
11:42:55 [ERROR] Failed to access device: HidApiError { message: "WriteFile: (0x00000001) Incorrect function." }; trying to reconnect...

**Comment by aarol** [comment]
It's still not working, that's unfortunate. I've been looking at Headset control's source (https://github.com/Sapd/HeadsetControl/tree/master) and I can't seem to spot any difference in my implementation versus theirs. Maybe I need to look harder when I have enough time

**Comment by gamerscircle** [comment]
I do appreciate it the effort and isn't as if I really need it, just nice to have an easy see reference.   Let me know if there is anything I can do to help.

**Comment by aarol** [comment]
It looked at the code and I think I found the issue, can you try version 1.5.1?

**Comment by gamerscircle** [comment]
I sure can, is it okay to install on top of the previous version?

**Comment by gamerscircle** [comment]
2024-11-28T18:00:34.8816834Z [INFO] Starting application
2024-11-28T18:00:34.8863957Z [INFO] Searching for connected headphones...
2024-11-28T18:00:34.9635928Z [INFO] Found headphone: SteelSeries Arctis 1 Wireless
2024-11-28T18:00:35.9712591Z [ERROR] Failed to access device: HidApiError { message: "WriteFile: (0x00000001) Incorrect function." }; trying to reconnect...
2024-11-28T18:00:36.8146389Z [INFO] Searching for connected headphones...
2024-11-28T18:00:36.8293016Z [INFO] Found headphone: SteelSeries Arctis 1 Wireless
2024-11-28T18:00:36.8294162Z [ERROR] Failed to access device: HidApiError { message: "WriteFile: (0x00000001) Incorrect function." }; trying to reconnect...
2024-11-28T18:00:38.0011445Z [INFO] Searching for connected headphones...
2024-11-28T18:00:38.0158226Z [INFO] Found headphone: SteelSeries Arctis 1 Wireless
2024-11-28T18:00:38.0158651Z [ERROR] Failed to access device: HidApiError { message: "WriteFile: (0x00000001) Incorrect function." }; trying to reconnect...

**Comment by aarol** [comment]
I've added some more logging and another thing that was missing from HeadsetControl's source. If that doesn't work then I genuinely have no idea what's causing this. You can try version 1.5.2 if you're still interested.

**Comment by gamerscircle** [comment]
I understand, there is only so much that can be done.  I did try it got the following:

2024-11-30T18:27:16.9650478Z [INFO] Starting application
2024-11-30T18:27:16.9653861Z [INFO] Version 1.5.2
2024-11-30T18:27:16.9677799Z [INFO] Searching for connected headphones...
2024-11-30T18:27:17.0456019Z [INFO] Found headphone: SteelSeries Arctis 1 Wireless
2024-11-30T18:27:18.0614663Z [ERROR] Failed to access device: writing [6, 18] to device

Caused by:
    hidapi error: WriteFile: (0x00000001) Incorrect function.; trying to reconnect...
2024-11-30T18:27:19.0619464Z [INFO] Searching for connected headphones...
2024-11-30T18:27:19.1395972Z [INFO] Found headphone: SteelSeries Arctis 1 Wireless
2024-11-30T18:27:19.1397782Z [ERROR] Failed to access device: writing [6, 18] to device

Caused by:
    hidapi error: WriteFile: (0x00000001) Incorrect function.; trying to reconnect...
2024-11-30T18:27:20.077555Z [INFO] Searching for connected headphones...
2024-11-30T18:27:20.0928514Z [INFO] Found headphone: SteelSeries Arctis 1 Wireless
2024-11-30T18:27:20.0928954Z [ERROR] Failed to access device: writing [6, 18] to device

**Comment by rupoase** [comment]
Similar issue with this one reported on another SteelSeries Arctis 1 Wireless device.
Things to mention that may be of importance: 
1. It's a work laptop, with some security policies on it.
2. I didn't installed the software via the PS1 script, due to the security policies that prevents us from running them
3. The executable is running as Administrator, but I think it doesn't make any difference
4. SteelSeries GG is running
5. Below is a snapshot from the debug app:

![Image](https://github.com/user-attachments/assets/6abf588e-b2e3-4f0c-8c12-56e298924574)

I'll try to run it on my regular PC, that is not managed by my org.

**Comment by guilhermelimait** [comment]
I have the same issue, it doesn't get the battery level not even on a personal pc with access to run powershell scripts.

**Comment by aarol** [comment]
@rupoase @guilhermelimait thank you for the report, I've released version 1.6.0 which fixed a bug where the wrong headphone model could be selected. Maybe that was causing it? I only own the Arctis Nova 7 myself, so unfortunately I can't test it.

**Comment by rupoase** [comment]
Thanks a lot for your effort @aarol   

For my case I have the following log now (still not working, but seems that it has more info now)

![Image](https://github.com/user-attachments/assets/23397a7f-fe1f-40cf-a983-051c1e32afad)

I got my hands on some Arctis Nova 5 Wireless and I'll be testing them as well with these releases.

**Comment by rupoase** [comment]
@aarol 
Back with my Arctis Nova 5 Wireless:

![Image](https://github.com/user-attachments/assets/997dad1e-2891-4e3f-959a-599b00ec6927)

**Comment by jens-maxon** [comment]
I still have this issue even with the latest version 2.1.2

`Caused by:
    hidapi error: WriteFile: (0x00000001) Incorrect function.; trying to reconnect...
2025-05-23T11:41:55.2003232Z [INFO] Searching for connected headphones...
2025-05-23T11:41:55.2354567Z [INFO] Found headphone: Arctis 1 Wireless
2025-05-23T11:41:55.2444779Z [ERROR] Failed to access device: writing [6, 18] to device`

**Comment by rupoase** [comment]
Trying 2.1.2 and it works with my Arctis Nova 5X, displaying the exact percentage (in my case 76%).
I'll update this comment with my tests on Arctis Nova 5 and Arctis 1 Wireless in the upcoming days.

Thanks for your hard work @aarol

**Comment by aarol** [comment]
I suspect that Arctis 1 Wireless is still not working for anyone, since I haven't been able to debug the issue myself. I've been looking that headsetcontrol's code a lot but still haven't found the reason for it.

**Comment by aarol** [comment]
@rupoase I think I know the reason for your Nova 5X not working. It was probably being read as a Nova 5, which had the correct battery range while Nova 5X didn't. I fixed that and put out a new release.

**Comment by rupoase** [comment]
> [@rupoase](https://github.com/rupoase) I think I know the reason for your Nova 5X not working. It was probably being read as a Nova 5, which had the correct battery range while Nova 5X didn't. I fixed that and put out a new release.

Indeed, I installed it now and it works <3

**Comment by gamerscircle** [comment]
I finally replaced my Arctic 1 Wireless and I was curious does this app only support the Steel Series?  I ask, as my new head set it a Logitech G PRO X 2 Lightspeed Wireless and again I have to launch the app to get a battery status, but the battery life seems much much longer then my Arctic 1 Wireless - so, my direct question is will this app support the Logitech line?

**Comment by aarol** [comment]
> so, my direct question is will this app support the Logitech line?

Probably not, since I don't have a Logitech headset to test with.

Also, looking at the HeadsetControl [device matrix](https://github.com/Sapd/HeadsetControl?tab=readme-ov-file#supported-headsets), it seems that they haven't found a way to get the battery level from G PRO X 2 headsets yet.

**Comment by gamerscircle** [comment]
Well - I don't need you to run out and get a headset for this. :)    thank you for the support on this and there might be another way.  There is something called LGSTrayBattery that might help.

**Comment by rupoase** [comment]
Quick update on the latest version (3.6.0):  
All my headsets (Arctis 1 Wireless, Nova 5 and Nova 5X) work nicely, since the last time I tested them, with 2.1.x
The issue I'm having on my work laptop is again the antivirus thing, but I think now that's something about the AV solution being too aggressive. On my PC and laptop at home I don't have any issues.

**Comment by aarol** [comment]
Since Arctis 1 Wireless seems to be working now for at least one person, I'll close this issue now. If the newest version doesn't work for someone else, we can reopen this issue.
